# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tK3bofK0Dj1oeg7cCLxV5OkIIccWv9nO
"""

import streamlit as st

st.write('Hello world!')

